### ISSUE TITLE
Wrong link for Pseudopotentials page in Materials Methodology section 

### ISSUE THREAD

**Issue by manaslkht** [materialsproject/public-docs#3]
Hello @mkhorton , 

I was reading about this POTCAR version that is being used on Materials Project and I came across a peculiar problem on Materials Project's webpage. 

On the "Calculation details" [page](https://docs.materialsproject.org/methodology/materials-methodology/calculation-details) of the "Materials Methodology" section,  if I click on the "Pseudopotentials" option (see screenshot for visual reference), it jumps to the "Pseudopotential" [page](https://docs.materialsproject.org/methodology/mof-methodology/calculation-parameters/psuedopotentials) for MOF methodology section instead of the "Pseudopotential" [page](https://docs.materialsproject.org/methodology/materials-methodology/calculation-details/pseudopotentials) of "Materials Methodology" section. 

<img width="857" alt="Screen Shot 2022-07-27 at 6 11 00 PM" src="https://user-images.githubusercontent.com/33138283/181398936-351f28cc-58ff-4135-82ab-89243ea5d79e.png">
 
This works fine if I click on the "Pseudopotential" option on the page tree structure on the left (see below)

<img width="293" alt="Screen Shot 2022-07-27 at 6 16 26 PM" src="https://user-images.githubusercontent.com/33138283/181399427-0ee37482-f837-4d7f-ac16-2c764ed36a9c.png">

This can potentially confuse the users. Could you please rectify this. 

Thank you!

Best,
Manas

**Comment by mkhorton** [comment]
I can send you an invite to edit the docs if you like, since you're within the collaboration. I received your message regarding pseudopotentials and will reply soon.

**Comment by manaslkht** [comment]
Sure. Will be happy to edit. My question on pseudopotentials was regarding this. The potentials used are correct, it is just that it was opening the wrong page which was the source of the confusion. Thanks to Ryan Kingsbury for pointing this out. 

Thank you!
