### ISSUE TITLE
Where are the previous documentations for interfacial reactions, Ehull, electrochemical window?

### ISSUE THREAD

**Issue by JiQi535** [materialsproject/public-docs#5]
Hi @mkhorton , I have been learning about methodologies in calculating energy above hull, interfacial reactions, and voltage stability analysis on the Materials Project documentations about phase diagram and grand potential phase diagram. However, I failed to find them on this newer version of MP online documentation. 

Could you let me know if those good documentations have been moved elsewhere? And will they be posted again in MP online doc in near future? Thanks.

**Comment by mkhorton** [comment]
For information on how to find older versions of the documentation, please see this:

https://docs.materialsproject.org/changes#documentation

All relevant information should be in the new documentation too, if not now then in the near future.
