### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by computron** [materialsproject/public-docs#6]
Not sure this is the correct repo but a link is broken here:

https://next-gen.materialsproject.org/api#documentation

"For detailed instructions on how to use the API to download data, please see the [Materials Project API Docs.](https://next-gen-docs.materialsproject.org/downloading-data/how-do-i-download-the-materials-project-database)"

**Comment by tschaume** [comment]
Thanks for reporting this. I've put a redirect in place a little while ago that should keep these links alive.
