### ISSUE TITLE
Dead links to the source codes

### ISSUE THREAD

**Issue by e-kwsm** [materialsproject/public-docs#7]
For example, the followings in <https://docs.materialsproject.org/downloading-data/using-the-api/getting-started> and <https://docs.materialsproject.org/downloading-data/using-the-api/querying-data#convenience-functions> are dead:

- [x] https://github.com/materialsproject/public-docs/blob/37b182da4aa9aed7452fb6f11ed039a4270381ec/downloading-data/using-the-api/getting-started.md#L36
- [ ] https://github.com/materialsproject/public-docs/blob/37b182da4aa9aed7452fb6f11ed039a4270381ec/downloading-data/using-the-api/querying-data.md#L100
-  [ ] https://github.com/materialsproject/public-docs/blob/37b182da4aa9aed7452fb6f11ed039a4270381ec/downloading-data/using-the-api/querying-data.md#L104

The second one seemed to be https://github.com/materialsproject/api/blob/v0.33.0/mp_api/client/routes/materials.py#L53-L178 and moved to a subdirectory, https://github.com/materialsproject/api/blob/v0.34.0/mp_api/client/routes/materials/materials.py.

Also, the file linked from below has been updated since the doc was written and the range is now wrong:

- [ ] https://github.com/materialsproject/public-docs/blob/37b182da4aa9aed7452fb6f11ed039a4270381ec/downloading-data/using-the-api/advanced-usage.md#L24

which must be https://github.com/materialsproject/api/blob/1845d1ebc447dbcaa0f22dc558594575e1081721/mp_api/client/core/client.py#L1042-L1078?

Here I would suggest pinning to the commits, as shown above, instead of "main" branch.

**Comment by kalvdans** [comment]
Yes, please pin to the commits.

**Comment by tschaume** [comment]
Thanks for reporting this and your patience. I've removed the outdated links and replaced them with URLs pointing to the [code documentation](https://materialsproject.github.io/api)

**Comment by kalvdans** [comment]
Thanks @tschaume ! Was the changes made in 9f0dfeadfa1f5da1b6cf9838224c0f295b1f53de ?

**Comment by tschaume** [comment]
Yes. The changes are all reflected on https://docs.materialsproject.org.
