### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by ak983819** [materialsproject/public-docs#8]
### Problem

Hi, I am 2nd year PhD student at the University of Houston. I am working on a model to predict some properties of fluoride composition.

I needed the value of all these features for all fluoride compositions present in the material project;
Space group number | Crystal system | Laue class | Crystal class | Inversion center | Polar axis | Reduced volume | Density | Average anisotropy (average between a/b,   b/c, c/a) | Electron density: number of   valence electrons per V per Z | Electron density (number of valence   electrons per V per atom) | Electron density (Gilman valence per V per   atom) | Electron density (outer shell per V per   atom

Could You please guide me on how I can use python to extract the values of these features?

Thanks 

### Proposed Solution

Can I get working code on it

**Comment by tschaume** [comment]
Please refer to our [forum](https://matsci.org/materials-project) for help and post your question there if an existing thread doesn't provide a solution.
